# Generated by Django 3.0.2 on 2020-02-13 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='body',
            field=models.CharField(default='None', max_length=1500, verbose_name='Body'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='subject',
            field=models.CharField(default='None', max_length=100, verbose_name='Subject'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='title',
            field=models.CharField(default='None', max_length=60, verbose_name='Title'),
            preserve_default=False,
        ),
    ]
